version: 0.2

phases:
  install:
    commands:
      - echo Installing nvm
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      - nvm install 14
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build # Replace with your actual build command if necessary
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: yes
